name: Sync Docs to gh-pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "Brayan-CVR"
          git config user.email "brayanv395@gmial.com"

      - name: Verificar contenido generado por Sphinx
        run: |
          ls -la docs/build/html/

      - name: Crear archivo .nojekyll
        run: |
          touch docs/build/html/.nojekyll

      - name: Copiar contenido a directorio temporal
        run: |
          mkdir -p ~/gh-pages-temp
          cp -R docs/build/html/* ~/gh-pages-temp/
          ls -la ~/gh-pages-temp/

      - name: Actualizar gh-pages
        run: |
          # Obtener la rama gh-pages remota
          git fetch origin gh-pages:gh-pages || echo "La rama gh-pages no existe aún"

          # Cambiar a gh-pages o crearla si no existe
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            # Forzar la sincronización con el remoto
            git reset --hard origin/gh-pages || echo "No se pudo resetear, continuando"
          else
            git checkout --orphan gh-pages
            git rm -rf . || echo "No hay nada que borrar en rama nueva"
          fi

          # Limpiar contenido excepto .git
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} + || echo "No hay contenido previo para limpiar"

          # Copiar nuevo contenido
          cp -R ~/gh-pages-temp/* .

          # Asegurar que .nojekyll está presente
          touch .nojekyll

          # Agregar todos los archivos
          git add .

          # Hacer commit solo si hay cambios
          if git diff-index --quiet HEAD --; then
            echo "No hay cambios que commitear"
          else
            git commit -m "Actualización de documentación $(date)"
            # Forzar push para sobrescribir cualquier cambio remoto
            git push --force origin gh-pages
          fi